GET http://localhost:8000/users

###
POST http://localhost:8000/login
Content-Type: application/json

{
    "name" : "ABC",
    "password" : "123123"
}


    "version": "1.0.0",
    "lockfileVersion": 2,
    "requires": true,
    "packages": {
        "": {
            "name": "case_study",
            "version": "1.0.0",
            "license": "ISC",
            "dependencies": {
                "bcrypt": "^5.0.1",
                "dotenv": "^16.0.1",
                "ejs": "^3.1.8",
                "express": "^4.18.1",
                "jquery": "^3.6.0",
                "mysql": "^2.18.1"
            },
            "devDependencies": {
                "nodemon": "^2.0.16"
            }
        },